(executable
 (public_name theory_dev)
 (name theory_dev)
 (link_flags
  (:standard -linkall))
 (preprocess
  (pps heft.ppx_heft ppx_deriving.show))
 (libraries
  domainslib
  heft
  heft.theories.nats
  heft.theories.conds
  heft.theories.wf
  heft.theories.lists
  heft.theories.bools
  heft.theories.sets
  heft.theories.pairs
  heft.theories.ocaml))
